# Generated by Django 3.2.7 on 2021-09-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
