# Generated by Django 3.2.7 on 2021-09-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_week_match_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='main.week'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='main.tour'),
        ),
        migrations.AlterField(
            model_name='week',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='main.tour'),
        ),
    ]
