# Generated by Django 3.2.7 on 2021-09-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210903_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('week__level',)},
        ),
    ]
