# Generated by Django 3.2.7 on 2021-09-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_match_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='average',
        ),
    ]
