# Generated by Django 3.2.7 on 2021-09-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_team_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='average',
            field=models.IntegerField(default=0),
        ),
    ]
