# Generated by Django 3.2.7 on 2021-09-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_team_average'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('week__level', 'id')},
        ),
    ]
