# Generated by Django 3.2.7 on 2022-11-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_match_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='drawn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='win',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
